In [136]:
import nltk 
import pandas as pd

In [137]:
df = pd.read_csv("IMDB_Dataset.csv")

In [138]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [139]:
import re 
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [140]:
df['review']=df['review'].apply(remove_html_tags)

In [141]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [142]:
# remove url example 
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [143]:
text1 = 'check out the https://www.kaggle.com/campux/notebook414152f'
text2 = 'check out the http://www.kaggle.com/campus/nothenoolm254'
text3 = 'Goggle search here www.google.com'

In [144]:
remove_url(text1)

'check out the '

In [145]:
remove_url(text2)

'check out the '

In [146]:
remove_url(text3)

'Goggle search here '

## Remove punctuation

In [147]:
import string
import time

print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [148]:
exclude=string.punctuation

In [149]:
def remove_puch(text):
    for char in exclude:
        text=text.replace(char,'')
    return text

In [150]:
text='string. with. punchuation?'

In [151]:
remove_puch(text)

'string with punchuation'

In [152]:
# second method is the fastest method 

def remove_puch1(text):
    return text.translate(str.maketrans('','',exclude))

In [153]:
remove_puch1(text)

'string with punchuation'

## spelling correction

In [154]:
from textblob import TextBlob

In [155]:
incorrect_word='corection duroing serval ggeneration aree moodify in the timee'
textblb =TextBlob(incorrect_word)
textblb.correct().string

'correction during several generation are modify in the time'

In [156]:
from nltk.corpus import stopwords

In [157]:
stopwords.words('English')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [158]:
def remove_stopwords(text):
    new_text=[]
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
            
    x=new_text[:]
    new_text.clear()
    return " ".join(x)

In [159]:
remove_stopwords('my name is ayan khan and i am form dholpur rajasthan and i am pursuing my b.tech from global institute of technology')

' name  ayan khan    form dholpur rajasthan    pursuing  b.tech  global institute  technology'

### Tokeniztion

In [160]:
var = "It is primarily concerned with providing computers the ability to process data encoded in natural language and is thus closely related to information retrieval, knowledge representation and computational linguistics, a subfield of linguistics. Typically data is collected in text corpora, using either rule-based, statistical or neural-based approaches of machine learning and deep learning."

In [161]:
var

'It is primarily concerned with providing computers the ability to process data encoded in natural language and is thus closely related to information retrieval, knowledge representation and computational linguistics, a subfield of linguistics. Typically data is collected in text corpora, using either rule-based, statistical or neural-based approaches of machine learning and deep learning.'

In [162]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [163]:
sent = sent_tokenize(var)

In [164]:
sent

['It is primarily concerned with providing computers the ability to process data encoded in natural language and is thus closely related to information retrieval, knowledge representation and computational linguistics, a subfield of linguistics.',
 'Typically data is collected in text corpora, using either rule-based, statistical or neural-based approaches of machine learning and deep learning.']

In [165]:
word = word_tokenize(var)

In [166]:
word

['It',
 'is',
 'primarily',
 'concerned',
 'with',
 'providing',
 'computers',
 'the',
 'ability',
 'to',
 'process',
 'data',
 'encoded',
 'in',
 'natural',
 'language',
 'and',
 'is',
 'thus',
 'closely',
 'related',
 'to',
 'information',
 'retrieval',
 ',',
 'knowledge',
 'representation',
 'and',
 'computational',
 'linguistics',
 ',',
 'a',
 'subfield',
 'of',
 'linguistics',
 '.',
 'Typically',
 'data',
 'is',
 'collected',
 'in',
 'text',
 'corpora',
 ',',
 'using',
 'either',
 'rule-based',
 ',',
 'statistical',
 'or',
 'neural-based',
 'approaches',
 'of',
 'machine',
 'learning',
 'and',
 'deep',
 'learning',
 '.']

In [167]:
from nltk.stem import LancasterStemmer, PorterStemmer, SnowballStemmer

In [168]:
l = LancasterStemmer() 
p = PorterStemmer()    
s = SnowballStemmer('english')

In [170]:
l.stem("changing")

'chang'

In [171]:
p.stem("changing")

'chang'

In [172]:
s.stem("changing")

'chang'

### Lemmatization

In [173]:
from nltk.stem import WordNetLemmatizer

wl = WordNetLemmatizer()
print(wl.lemmatize("mice", pos="n"))

mouse